// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import Portfolio from './Portfolio';

export {
	Hero,
	Portfolio,
};

export const components = {
	hero: Hero,
	portfolio: Portfolio,
};
