// Types
import { GetStaticProps, NextPage } from "next";

import { SliceZone } from "@prismicio/react";

import { createClient } from "../prismicio";
import { components } from "../slices";

import Head from "next/head";

const Home: NextPage = ({ page }) => {
  return (
    <div>
      <Head>
        <title>Carly Fisher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SliceZone slices={page.data.slices} components={components} />
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async ({ previewData }) => {
  const client = createClient({ previewData });

  const page = await client.getSingle("homepage");

  return {
    props: {
      page,
    },
  };
};
