// Types
import { GetStaticProps } from "next";

// Components
import { Layout } from "../components/Layout";

// Data Fetching from Prismic
// import { getHeaderProps } from "../utils/fetchData";
// import { getContactProps } from "../utils/fetchData/getContactProps";

// Sanity
import { sanityClient } from "../sanity";
import { PageBuilder } from "../components/PageBuilder";

import Head from "next/head";

const Home = ({ page, header }) => {
  return (
    <div>
      <Head>
        <title>Carly Fisher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-x-hidden">
        <Layout header={header}>
          <>
            <PageBuilder sections={page.sections} />
          </>
        </Layout>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async ({ previewData }) => {
  const query = `*[_type == "homepage"]{
    sections[] {
      _type == "hero" => {
      ...
      },
      _type == "portfolio" => {
        ...,
        pastWorks[]->{date, slug, name, summary, image}
      },
      _type == "skillGallery" => {
        ...,
        skills[]->{
          image {
            ...,
            source {
              "": asset->{
                url,
                "": metadata{dimensions}
              }
            }
          }, 
          name,
          slug
        }
      },
      _type == "contact" => {
        ...,
        contactLinks[] {icon, link, linkText}
      }
    }
  }`;

  let page = await sanityClient.fetch(query);
  page = page[0];

  // const header = await getHeaderProps({ client });

  return {
    props: {
      page,
      // header,
    },
  };
};
